image: python:latest

variables:
  NOME_TESTE: "TESTES django_girls"
  NOME_RUN: "COMPILAÇÃO django_girls"


before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
  - echo "Rodando: $NOME_TESTE!"

run:
  script:
  - echo "Rodando: $NOME_RUN!"
  #- python setup.py bdist_wheel
  # an alternative approach is to install and run:
  #- pip install dist/*
  # run the command here
  #artifacts:
  #  paths:
  #  - dist/*.whl
