# Generated by Django 2.0 on 2020-06-29 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200629_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='knowledge_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.KnowledgeLevel'),
        ),
    ]
