# Generated by Django 2.0 on 2020-06-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190227_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='migrated-article', max_length=200),
        ),
    ]
