# Generated by Django 2.0 on 2020-06-24 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(default='Dark Red', max_length=20)),
                ('rgb', models.CharField(default='#cf0a2c', max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default='migrated-post', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.Color'),
        ),
    ]
